class = "[Lnet/minecraft/world/level/levelgen/structure/placement/AbstractSpreadingStructurePlacement$FrequencyReductionMethod;"

[[member]]
name = "clone"
descriptor = "()Ljava/lang/Object;"
kind = "builtin"
references = 1
