class = "com/sun/jna/platform/unix/aix/Perfstat$perfstat_process_t"

[[member]]
name = "size"
descriptor = "()I"
kind = "builtin"
references = 2

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 1

[[member]]
name = "toArray"
descriptor = "(I)[Lcom/sun/jna/Structure;"
kind = "builtin"
references = 1

[[member]]
name = "scpu_time"
descriptor = "D"
kind = "builtin"
references = 1

[[member]]
name = "ucpu_time"
descriptor = "D"
kind = "builtin"
references = 1

[[member]]
name = "pid"
descriptor = "J"
kind = "builtin"
references = 1
