class = "com/sun/jna/platform/win32/WinPerf$PERF_COUNTER_DEFINITION"

[[member]]
name = "<init>"
descriptor = "(Lcom/sun/jna/Pointer;)V"
kind = "builtin"
references = 1

[[member]]
name = "ByteLength"
descriptor = "I"
kind = "builtin"
references = 1

[[member]]
name = "CounterNameTitleIndex"
descriptor = "I"
kind = "builtin"
references = 2

[[member]]
name = "CounterOffset"
descriptor = "I"
kind = "builtin"
references = 1

[[member]]
name = "CounterSize"
descriptor = "I"
kind = "builtin"
references = 1
