class = "java/util/ArrayList"

[[member]]
name = "size"
descriptor = "()I"
kind = "builtin"
references = 69

[[member]]
name = "getFirst"
descriptor = "()Ljava/lang/Object;"
kind = "builtin"
references = 1

[[member]]
name = "iterator"
descriptor = "()Ljava/util/Iterator;"
kind = "builtin"
references = 37

[[member]]
name = "stream"
descriptor = "()Ljava/util/stream/Stream;"
kind = "builtin"
references = 3

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 627

[[member]]
name = "clear"
descriptor = "()V"
kind = "builtin"
references = 9

[[member]]
name = "trimToSize"
descriptor = "()V"
kind = "builtin"
references = 1

[[member]]
name = "isEmpty"
descriptor = "()Z"
kind = "builtin"
references = 14

[[member]]
name = "get"
descriptor = "(I)Ljava/lang/Object;"
kind = "builtin"
references = 65

[[member]]
name = "remove"
descriptor = "(I)Ljava/lang/Object;"
kind = "builtin"
references = 5

[[member]]
name = "<init>"
descriptor = "(I)V"
kind = "builtin"
references = 195

[[member]]
name = "ensureCapacity"
descriptor = "(I)V"
kind = "builtin"
references = 2

[[member]]
name = "set"
descriptor = "(ILjava/lang/Object;)Ljava/lang/Object;"
kind = "builtin"
references = 4

[[member]]
name = "add"
descriptor = "(ILjava/lang/Object;)V"
kind = "builtin"
references = 3

[[member]]
name = "add"
descriptor = "(Ljava/lang/Object;)Z"
kind = "builtin"
references = 92

[[member]]
name = "contains"
descriptor = "(Ljava/lang/Object;)Z"
kind = "builtin"
references = 1

[[member]]
name = "remove"
descriptor = "(Ljava/lang/Object;)Z"
kind = "builtin"
references = 2

[[member]]
name = "<init>"
descriptor = "(Ljava/util/Collection;)V"
kind = "builtin"
references = 77

[[member]]
name = "addAll"
descriptor = "(Ljava/util/Collection;)Z"
kind = "builtin"
references = 5

[[member]]
name = "sort"
descriptor = "(Ljava/util/Comparator;)V"
kind = "builtin"
references = 2

[[member]]
name = "toArray"
descriptor = "([Ljava/lang/Object;)[Ljava/lang/Object;"
kind = "builtin"
references = 8
