class = "java/io/ObjectInputStream"

[[member]]
name = "readObject"
descriptor = "()Ljava/lang/Object;"
kind = "builtin"
references = 1

[[member]]
name = "close"
descriptor = "()V"
kind = "builtin"
references = 2

[[member]]
name = "<init>"
descriptor = "(Ljava/io/InputStream;)V"
kind = "builtin"
references = 2
