class = "java/util/GregorianCalendar"

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 1

[[member]]
name = "clear"
descriptor = "()V"
kind = "builtin"
references = 1

[[member]]
name = "get"
descriptor = "(I)I"
kind = "builtin"
references = 7

[[member]]
name = "<init>"
descriptor = "(III)V"
kind = "builtin"
references = 1

[[member]]
name = "<init>"
descriptor = "(IIIIII)V"
kind = "builtin"
references = 1

[[member]]
name = "setTime"
descriptor = "(Ljava/util/Date;)V"
kind = "builtin"
references = 1

[[member]]
name = "<init>"
descriptor = "(Ljava/util/TimeZone;)V"
kind = "builtin"
references = 5
