class = "java/util/concurrent/DelayQueue"

[[member]]
name = "poll"
descriptor = "()Ljava/util/concurrent/Delayed;"
kind = "builtin"
references = 2

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 1

[[member]]
name = "add"
descriptor = "(Ljava/util/concurrent/Delayed;)Z"
kind = "builtin"
references = 1
