class = "java/util/concurrent/locks/ReentrantReadWriteLock"

[[member]]
name = "getReadLockCount"
descriptor = "()I"
kind = "builtin"
references = 2

[[member]]
name = "readLock"
descriptor = "()Ljava/util/concurrent/locks/ReentrantReadWriteLock$ReadLock;"
kind = "builtin"
references = 10

[[member]]
name = "writeLock"
descriptor = "()Ljava/util/concurrent/locks/ReentrantReadWriteLock$WriteLock;"
kind = "builtin"
references = 15

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 9

[[member]]
name = "isWriteLocked"
descriptor = "()Z"
kind = "builtin"
references = 2

[[member]]
name = "<init>"
descriptor = "(Z)V"
kind = "builtin"
references = 1
