class = "java/lang/ExceptionInInitializerError"

[[member]]
name = "<init>"
descriptor = "(Ljava/lang/String;)V"
kind = "builtin"
references = 3

[[member]]
name = "<init>"
descriptor = "(Ljava/lang/Throwable;)V"
kind = "builtin"
references = 6
