class = "java/io/DataOutputStream"

[[member]]
name = "close"
descriptor = "()V"
kind = "builtin"
references = 8

[[member]]
name = "<init>"
descriptor = "(Ljava/io/OutputStream;)V"
kind = "builtin"
references = 4
