class = "java/lang/InterruptedException"

[[member]]
name = "getMessage"
descriptor = "()Ljava/lang/String;"
kind = "builtin"
references = 2

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 4

[[member]]
name = "<init>"
descriptor = "(Ljava/lang/String;)V"
kind = "builtin"
references = 2
