class = "java/util/function/Function"

[[member]]
name = "identity"
descriptor = "()Ljava/util/function/Function;"
kind = "builtin"
references = 104

[[member]]
name = "apply"
descriptor = "(Ljava/lang/Object;)Ljava/lang/Object;"
kind = "builtin"
references = 862

[[member]]
name = "andThen"
descriptor = "(Ljava/util/function/Function;)Ljava/util/function/Function;"
kind = "builtin"
references = 7

[[member]]
name = "compose"
descriptor = "(Ljava/util/function/Function;)Ljava/util/function/Function;"
kind = "builtin"
references = 5
