class = "java/lang/ArrayIndexOutOfBoundsException"

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 23

[[member]]
name = "<init>"
descriptor = "(I)V"
kind = "builtin"
references = 3

[[member]]
name = "<init>"
descriptor = "(Ljava/lang/String;)V"
kind = "builtin"
references = 28
