class = "java/time/ZonedDateTime"

[[member]]
name = "toInstant"
descriptor = "()Ljava/time/Instant;"
kind = "builtin"
references = 1

[[member]]
name = "parse"
descriptor = "(Ljava/lang/CharSequence;)Ljava/time/ZonedDateTime;"
kind = "builtin"
references = 1
