class = "java/util/Spliterator"

[[member]]
name = "characteristics"
descriptor = "()I"
kind = "builtin"
references = 2

[[member]]
name = "estimateSize"
descriptor = "()J"
kind = "builtin"
references = 54

[[member]]
name = "getExactSizeIfKnown"
descriptor = "()J"
kind = "builtin"
references = 10

[[member]]
name = "hasCharacteristics"
descriptor = "(I)Z"
kind = "builtin"
references = 1

[[member]]
name = "forEachRemaining"
descriptor = "(Ljava/util/function/Consumer;)V"
kind = "builtin"
references = 10

[[member]]
name = "tryAdvance"
descriptor = "(Ljava/util/function/Consumer;)Z"
kind = "builtin"
references = 16
