class = "javax/management/MBeanInfo"

[[member]]
name = "<init>"
descriptor = "(Ljava/lang/String;Ljava/lang/String;[Ljavax/management/MBeanAttributeInfo;[Ljavax/management/MBeanConstructorInfo;[Ljavax/management/MBeanOperationInfo;[Ljavax/management/MBeanNotificationInfo;)V"
kind = "builtin"
references = 1
