class = "java/util/SequencedSet"

[[member]]
name = "add"
descriptor = "(Ljava/lang/Object;)Z"
kind = "builtin"
references = 1

[[member]]
name = "contains"
descriptor = "(Ljava/lang/Object;)Z"
kind = "builtin"
references = 2

[[member]]
name = "remove"
descriptor = "(Ljava/lang/Object;)Z"
kind = "builtin"
references = 1
