class = "java/util/stream/Stream"

[[member]]
name = "count"
descriptor = "()J"
kind = "builtin"
references = 18

[[member]]
name = "iterator"
descriptor = "()Ljava/util/Iterator;"
kind = "builtin"
references = 12

[[member]]
name = "toList"
descriptor = "()Ljava/util/List;"
kind = "builtin"
references = 252

[[member]]
name = "findAny"
descriptor = "()Ljava/util/Optional;"
kind = "builtin"
references = 14

[[member]]
name = "findFirst"
descriptor = "()Ljava/util/Optional;"
kind = "builtin"
references = 59

[[member]]
name = "spliterator"
descriptor = "()Ljava/util/Spliterator;"
kind = "builtin"
references = 2

[[member]]
name = "parallel"
descriptor = "()Ljava/util/stream/BaseStream;"
kind = "builtin"
references = 2

[[member]]
name = "builder"
descriptor = "()Ljava/util/stream/Stream$Builder;"
kind = "builtin"
references = 7

[[member]]
name = "distinct"
descriptor = "()Ljava/util/stream/Stream;"
kind = "builtin"
references = 12

[[member]]
name = "empty"
descriptor = "()Ljava/util/stream/Stream;"
kind = "builtin"
references = 49

[[member]]
name = "sorted"
descriptor = "()Ljava/util/stream/Stream;"
kind = "builtin"
references = 14

[[member]]
name = "close"
descriptor = "()V"
kind = "builtin"
references = 34

[[member]]
name = "isParallel"
descriptor = "()Z"
kind = "builtin"
references = 2

[[member]]
name = "limit"
descriptor = "(J)Ljava/util/stream/Stream;"
kind = "builtin"
references = 16

[[member]]
name = "skip"
descriptor = "(J)Ljava/util/stream/Stream;"
kind = "builtin"
references = 4

[[member]]
name = "of"
descriptor = "(Ljava/lang/Object;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 43

[[member]]
name = "reduce"
descriptor = "(Ljava/lang/Object;Ljava/util/function/BiFunction;Ljava/util/function/BinaryOperator;)Ljava/lang/Object;"
kind = "builtin"
references = 2

[[member]]
name = "reduce"
descriptor = "(Ljava/lang/Object;Ljava/util/function/BinaryOperator;)Ljava/lang/Object;"
kind = "builtin"
references = 12

[[member]]
name = "onClose"
descriptor = "(Ljava/lang/Runnable;)Ljava/util/stream/BaseStream;"
kind = "builtin"
references = 5

[[member]]
name = "max"
descriptor = "(Ljava/util/Comparator;)Ljava/util/Optional;"
kind = "builtin"
references = 6

[[member]]
name = "min"
descriptor = "(Ljava/util/Comparator;)Ljava/util/Optional;"
kind = "builtin"
references = 10

[[member]]
name = "sorted"
descriptor = "(Ljava/util/Comparator;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 50

[[member]]
name = "mapMulti"
descriptor = "(Ljava/util/function/BiConsumer;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 3

[[member]]
name = "reduce"
descriptor = "(Ljava/util/function/BinaryOperator;)Ljava/util/Optional;"
kind = "builtin"
references = 6

[[member]]
name = "peek"
descriptor = "(Ljava/util/function/Consumer;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 3

[[member]]
name = "forEach"
descriptor = "(Ljava/util/function/Consumer;)V"
kind = "builtin"
references = 206

[[member]]
name = "forEachOrdered"
descriptor = "(Ljava/util/function/Consumer;)V"
kind = "builtin"
references = 2

[[member]]
name = "flatMap"
descriptor = "(Ljava/util/function/Function;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 108

[[member]]
name = "map"
descriptor = "(Ljava/util/function/Function;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 608

[[member]]
name = "toArray"
descriptor = "(Ljava/util/function/IntFunction;)[Ljava/lang/Object;"
kind = "builtin"
references = 39

[[member]]
name = "dropWhile"
descriptor = "(Ljava/util/function/Predicate;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 7

[[member]]
name = "filter"
descriptor = "(Ljava/util/function/Predicate;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 393

[[member]]
name = "allMatch"
descriptor = "(Ljava/util/function/Predicate;)Z"
kind = "builtin"
references = 20

[[member]]
name = "anyMatch"
descriptor = "(Ljava/util/function/Predicate;)Z"
kind = "builtin"
references = 56

[[member]]
name = "noneMatch"
descriptor = "(Ljava/util/function/Predicate;)Z"
kind = "builtin"
references = 11

[[member]]
name = "generate"
descriptor = "(Ljava/util/function/Supplier;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 2

[[member]]
name = "mapToDouble"
descriptor = "(Ljava/util/function/ToDoubleFunction;)Ljava/util/stream/DoubleStream;"
kind = "builtin"
references = 3

[[member]]
name = "mapToInt"
descriptor = "(Ljava/util/function/ToIntFunction;)Ljava/util/stream/IntStream;"
kind = "builtin"
references = 32

[[member]]
name = "mapToLong"
descriptor = "(Ljava/util/function/ToLongFunction;)Ljava/util/stream/LongStream;"
kind = "builtin"
references = 7

[[member]]
name = "collect"
descriptor = "(Ljava/util/stream/Collector;)Ljava/lang/Object;"
kind = "builtin"
references = 319

[[member]]
name = "concat"
descriptor = "(Ljava/util/stream/Stream;Ljava/util/stream/Stream;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 31

[[member]]
name = "of"
descriptor = "([Ljava/lang/Object;)Ljava/util/stream/Stream;"
kind = "builtin"
references = 65
