class = "java/lang/IndexOutOfBoundsException"

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 148

[[member]]
name = "<init>"
descriptor = "(I)V"
kind = "builtin"
references = 3

[[member]]
name = "<init>"
descriptor = "(Ljava/lang/String;)V"
kind = "builtin"
references = 259
