class = "java/lang/Boolean"

[[member]]
name = "toString"
descriptor = "()Ljava/lang/String;"
kind = "builtin"
references = 3

[[member]]
name = "booleanValue"
descriptor = "()Z"
kind = "builtin"
references = 1025

[[member]]
name = "equals"
descriptor = "(Ljava/lang/Object;)Z"
kind = "builtin"
references = 12

[[member]]
name = "valueOf"
descriptor = "(Ljava/lang/String;)Ljava/lang/Boolean;"
kind = "builtin"
references = 11

[[member]]
name = "parseBoolean"
descriptor = "(Ljava/lang/String;)Z"
kind = "builtin"
references = 25

[[member]]
name = "valueOf"
descriptor = "(Z)Ljava/lang/Boolean;"
kind = "builtin"
references = 1345

[[member]]
name = "toString"
descriptor = "(Z)Ljava/lang/String;"
kind = "builtin"
references = 11

[[member]]
name = "compare"
descriptor = "(ZZ)I"
kind = "builtin"
references = 2

[[member]]
name = "FALSE"
descriptor = "Ljava/lang/Boolean;"
kind = "builtin"
references = 11

[[member]]
name = "TRUE"
descriptor = "Ljava/lang/Boolean;"
kind = "builtin"
references = 29

[[member]]
name = "TYPE"
descriptor = "Ljava/lang/Class;"
kind = "builtin"
references = 19
