class = "java/io/InputStreamReader"

[[member]]
name = "read"
descriptor = "()I"
kind = "builtin"
references = 2

[[member]]
name = "close"
descriptor = "()V"
kind = "builtin"
references = 2

[[member]]
name = "<init>"
descriptor = "(Ljava/io/InputStream;Ljava/lang/String;)V"
kind = "builtin"
references = 3

[[member]]
name = "<init>"
descriptor = "(Ljava/io/InputStream;Ljava/nio/charset/Charset;)V"
kind = "builtin"
references = 19
