class = "java/io/FileNotFoundException"

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 2

[[member]]
name = "<init>"
descriptor = "(Ljava/lang/String;)V"
kind = "builtin"
references = 10

[[member]]
name = "initCause"
descriptor = "(Ljava/lang/Throwable;)Ljava/lang/Throwable;"
kind = "builtin"
references = 1
