class = "java/util/TreeMap"

[[member]]
name = "clone"
descriptor = "()Ljava/lang/Object;"
kind = "builtin"
references = 2

[[member]]
name = "descendingMap"
descriptor = "()Ljava/util/NavigableMap;"
kind = "builtin"
references = 1

[[member]]
name = "entrySet"
descriptor = "()Ljava/util/Set;"
kind = "builtin"
references = 1

[[member]]
name = "keySet"
descriptor = "()Ljava/util/Set;"
kind = "builtin"
references = 1

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 35

[[member]]
name = "isEmpty"
descriptor = "()Z"
kind = "builtin"
references = 1

[[member]]
name = "get"
descriptor = "(Ljava/lang/Object;)Ljava/lang/Object;"
kind = "builtin"
references = 3

[[member]]
name = "containsKey"
descriptor = "(Ljava/lang/Object;)Z"
kind = "builtin"
references = 1

[[member]]
name = "put"
descriptor = "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"
kind = "builtin"
references = 10

[[member]]
name = "<init>"
descriptor = "(Ljava/util/Comparator;)V"
kind = "builtin"
references = 7

[[member]]
name = "<init>"
descriptor = "(Ljava/util/Map;)V"
kind = "builtin"
references = 2
