class = "java/lang/reflect/Modifier"

[[member]]
name = "isAbstract"
descriptor = "(I)Z"
kind = "builtin"
reason = "closed-world"
references = 2

[[member]]
name = "isFinal"
descriptor = "(I)Z"
kind = "builtin"
reason = "closed-world"
references = 2

[[member]]
name = "isInterface"
descriptor = "(I)Z"
kind = "builtin"
reason = "closed-world"
references = 1

[[member]]
name = "isPublic"
descriptor = "(I)Z"
kind = "builtin"
reason = "closed-world"
references = 4

[[member]]
name = "isStatic"
descriptor = "(I)Z"
kind = "builtin"
reason = "closed-world"
references = 11
