class = "java/util/stream/BaseStream"

[[member]]
name = "iterator"
descriptor = "()Ljava/util/Iterator;"
kind = "builtin"
references = 5

[[member]]
name = "close"
descriptor = "()V"
kind = "builtin"
references = 5
