class = "java/util/NoSuchElementException"

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 1710

[[member]]
name = "<init>"
descriptor = "(Ljava/lang/String;)V"
kind = "builtin"
references = 5
