class = "java/io/OutputStream"

[[member]]
name = "<init>"
descriptor = "()V"
kind = "builtin"
references = 15

[[member]]
name = "close"
descriptor = "()V"
kind = "builtin"
references = 41

[[member]]
name = "flush"
descriptor = "()V"
kind = "builtin"
references = 12

[[member]]
name = "write"
descriptor = "(I)V"
kind = "builtin"
references = 14

[[member]]
name = "write"
descriptor = "([B)V"
kind = "builtin"
references = 16

[[member]]
name = "write"
descriptor = "([BII)V"
kind = "builtin"
references = 23
