class = "javax/script/ScriptEngineFactory"

[[member]]
name = "getEngineName"
descriptor = "()Ljava/lang/String;"
kind = "builtin"
references = 1

[[member]]
name = "getEngineVersion"
descriptor = "()Ljava/lang/String;"
kind = "builtin"
references = 1

[[member]]
name = "getLanguageName"
descriptor = "()Ljava/lang/String;"
kind = "builtin"
references = 1

[[member]]
name = "getNames"
descriptor = "()Ljava/util/List;"
kind = "builtin"
references = 2

[[member]]
name = "getScriptEngine"
descriptor = "()Ljavax/script/ScriptEngine;"
kind = "builtin"
references = 1

[[member]]
name = "getParameter"
descriptor = "(Ljava/lang/String;)Ljava/lang/Object;"
kind = "builtin"
references = 2
