class = "org/lwjgl/vulkan/VkImageMemoryBarrier2"

[[member]]
name = "calloc"
descriptor = "(ILorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/vulkan/VkImageMemoryBarrier2$Buffer;"
kind = "builtin"
references = 2
