class = "org/lwjgl/vulkan/VkApplicationInfo"

[[member]]
name = "sType$Default"
descriptor = "()Lorg/lwjgl/vulkan/VkApplicationInfo;"
kind = "builtin"
references = 1

[[member]]
name = "apiVersion"
descriptor = "(I)Lorg/lwjgl/vulkan/VkApplicationInfo;"
kind = "builtin"
references = 1

[[member]]
name = "applicationVersion"
descriptor = "(I)Lorg/lwjgl/vulkan/VkApplicationInfo;"
kind = "builtin"
references = 1

[[member]]
name = "engineVersion"
descriptor = "(I)Lorg/lwjgl/vulkan/VkApplicationInfo;"
kind = "builtin"
references = 1

[[member]]
name = "pApplicationName"
descriptor = "(Ljava/nio/ByteBuffer;)Lorg/lwjgl/vulkan/VkApplicationInfo;"
kind = "builtin"
references = 1

[[member]]
name = "pEngineName"
descriptor = "(Ljava/nio/ByteBuffer;)Lorg/lwjgl/vulkan/VkApplicationInfo;"
kind = "builtin"
references = 1

[[member]]
name = "calloc"
descriptor = "(Lorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/vulkan/VkApplicationInfo;"
kind = "builtin"
references = 1
