class = "org/lwjgl/vulkan/VkDescriptorImageInfo"

[[member]]
name = "calloc"
descriptor = "(ILorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/vulkan/VkDescriptorImageInfo$Buffer;"
kind = "builtin"
references = 1
