class = "org/lwjgl/vulkan/VkCalibratedTimestampInfoEXT"

[[member]]
name = "calloc"
descriptor = "(ILorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/vulkan/VkCalibratedTimestampInfoEXT$Buffer;"
kind = "builtin"
references = 1
