class = "org/lwjgl/util/vma/VmaAllocatorCreateInfo"

[[member]]
name = "vulkanApiVersion"
descriptor = "(I)Lorg/lwjgl/util/vma/VmaAllocatorCreateInfo;"
kind = "builtin"
references = 1

[[member]]
name = "calloc"
descriptor = "(Lorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/util/vma/VmaAllocatorCreateInfo;"
kind = "builtin"
references = 1

[[member]]
name = "pVulkanFunctions"
descriptor = "(Lorg/lwjgl/util/vma/VmaVulkanFunctions;)Lorg/lwjgl/util/vma/VmaAllocatorCreateInfo;"
kind = "builtin"
references = 1

[[member]]
name = "device"
descriptor = "(Lorg/lwjgl/vulkan/VkDevice;)Lorg/lwjgl/util/vma/VmaAllocatorCreateInfo;"
kind = "builtin"
references = 1

[[member]]
name = "instance"
descriptor = "(Lorg/lwjgl/vulkan/VkInstance;)Lorg/lwjgl/util/vma/VmaAllocatorCreateInfo;"
kind = "builtin"
references = 1

[[member]]
name = "physicalDevice"
descriptor = "(Lorg/lwjgl/vulkan/VkPhysicalDevice;)Lorg/lwjgl/util/vma/VmaAllocatorCreateInfo;"
kind = "builtin"
references = 1
