class = "org/lwjgl/vulkan/VkSemaphoreSubmitInfo"

[[member]]
name = "calloc"
descriptor = "(ILorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/vulkan/VkSemaphoreSubmitInfo$Buffer;"
kind = "builtin"
references = 2
