class = "org/lwjgl/vulkan/VkPipelineColorBlendAttachmentState"

[[member]]
name = "calloc"
descriptor = "(ILorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/vulkan/VkPipelineColorBlendAttachmentState$Buffer;"
kind = "builtin"
references = 1
