class = "org/lwjgl/vulkan/VkCommandBufferSubmitInfo"

[[member]]
name = "calloc"
descriptor = "(ILorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/vulkan/VkCommandBufferSubmitInfo$Buffer;"
kind = "builtin"
references = 1
