class = "org/lwjgl/sdl/SDL_Rect"

[[member]]
name = "h"
descriptor = "()I"
kind = "builtin"
references = 2

[[member]]
name = "w"
descriptor = "()I"
kind = "builtin"
references = 2

[[member]]
name = "x"
descriptor = "()I"
kind = "builtin"
references = 2

[[member]]
name = "y"
descriptor = "()I"
kind = "builtin"
references = 2

[[member]]
name = "malloc"
descriptor = "(ILorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/sdl/SDL_Rect$Buffer;"
kind = "builtin"
references = 1

[[member]]
name = "malloc"
descriptor = "(Lorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/sdl/SDL_Rect;"
kind = "builtin"
references = 2
