class = "org/lwjgl/opengl/GL"

[[member]]
name = "createCapabilities"
descriptor = "()Lorg/lwjgl/opengl/GLCapabilities;"
kind = "builtin"
references = 1

[[member]]
name = "getCapabilities"
descriptor = "()Lorg/lwjgl/opengl/GLCapabilities;"
kind = "builtin"
references = 1

[[member]]
name = "getFunctionProvider"
descriptor = "()Lorg/lwjgl/system/FunctionProvider;"
kind = "builtin"
references = 3
