class = "org/lwjgl/vulkan/VkCommandBufferAllocateInfo"

[[member]]
name = "sType$Default"
descriptor = "()Lorg/lwjgl/vulkan/VkCommandBufferAllocateInfo;"
kind = "builtin"
references = 1

[[member]]
name = "commandBufferCount"
descriptor = "(I)Lorg/lwjgl/vulkan/VkCommandBufferAllocateInfo;"
kind = "builtin"
references = 1

[[member]]
name = "level"
descriptor = "(I)Lorg/lwjgl/vulkan/VkCommandBufferAllocateInfo;"
kind = "builtin"
references = 1

[[member]]
name = "commandPool"
descriptor = "(J)Lorg/lwjgl/vulkan/VkCommandBufferAllocateInfo;"
kind = "builtin"
references = 1

[[member]]
name = "calloc"
descriptor = "(Lorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/vulkan/VkCommandBufferAllocateInfo;"
kind = "builtin"
references = 1
