class = "org/lwjgl/vulkan/VkWriteDescriptorSet"

[[member]]
name = "sType$Default"
descriptor = "()Lorg/lwjgl/vulkan/VkWriteDescriptorSet;"
kind = "builtin"
references = 1

[[member]]
name = "descriptorCount"
descriptor = "(I)Lorg/lwjgl/vulkan/VkWriteDescriptorSet;"
kind = "builtin"
references = 1

[[member]]
name = "descriptorType"
descriptor = "(I)Lorg/lwjgl/vulkan/VkWriteDescriptorSet;"
kind = "builtin"
references = 3

[[member]]
name = "dstArrayElement"
descriptor = "(I)Lorg/lwjgl/vulkan/VkWriteDescriptorSet;"
kind = "builtin"
references = 1

[[member]]
name = "dstBinding"
descriptor = "(I)Lorg/lwjgl/vulkan/VkWriteDescriptorSet;"
kind = "builtin"
references = 1

[[member]]
name = "calloc"
descriptor = "(ILorg/lwjgl/system/MemoryStack;)Lorg/lwjgl/vulkan/VkWriteDescriptorSet$Buffer;"
kind = "builtin"
references = 1

[[member]]
name = "pTexelBufferView"
descriptor = "(Ljava/nio/LongBuffer;)Lorg/lwjgl/vulkan/VkWriteDescriptorSet;"
kind = "builtin"
references = 1

[[member]]
name = "pBufferInfo"
descriptor = "(Lorg/lwjgl/vulkan/VkDescriptorBufferInfo$Buffer;)Lorg/lwjgl/vulkan/VkWriteDescriptorSet;"
kind = "builtin"
references = 1

[[member]]
name = "pImageInfo"
descriptor = "(Lorg/lwjgl/vulkan/VkDescriptorImageInfo$Buffer;)Lorg/lwjgl/vulkan/VkWriteDescriptorSet;"
kind = "builtin"
references = 1
