[package]
name = "jars-core"
edition = "2024"
version.workspace = true
description.workspace = true

[dependencies]
jars-stdlib = { path = "../jars-stdlib" }
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
prettyplease.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
serde.workspace = true
toml.workspace = true
